# Generated by Django 5.0.1 on 2024-02-03 14:35

import shorter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0003_alter_link_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='key',
            field=models.CharField(default=shorter.models.generate_unique_key, editable=False, max_length=6, unique=True),
        ),
    ]
