# Generated by Django 5.0.1 on 2024-02-06 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0007_rename_url_link_urls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='urls',
            new_name='url',
        ),
    ]
